//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAuto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Taki : global::System.Configuration.ApplicationSettingsBase {
        
        private static Taki defaultInstance = ((Taki)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Taki())));
        
        public static Taki Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int số_luồng {
            get {
                return ((int)(this["số_luồng"]));
            }
            set {
                this["số_luồng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool check_làm_nhiệm_vụ {
            get {
                return ((bool)(this["check_làm_nhiệm_vụ"]));
            }
            set {
                this["check_làm_nhiệm_vụ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool check_tạo_post {
            get {
                return ((bool)(this["check_tạo_post"]));
            }
            set {
                this["check_tạo_post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool check_mua_coin {
            get {
                return ((bool)(this["check_mua_coin"]));
            }
            set {
                this["check_mua_coin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool check_stake {
            get {
                return ((bool)(this["check_stake"]));
            }
            set {
                this["check_stake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool check_Give_Taki {
            get {
                return ((bool)(this["check_Give_Taki"]));
            }
            set {
                this["check_Give_Taki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool check_thực_hiện_mời {
            get {
                return ((bool)(this["check_thực_hiện_mời"]));
            }
            set {
                this["check_thực_hiện_mời"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool check_xoá_tài_khoản {
            get {
                return ((bool)(this["check_xoá_tài_khoản"]));
            }
            set {
                this["check_xoá_tài_khoản"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txt_Wallet {
            get {
                return ((string)(this["txt_Wallet"]));
            }
            set {
                this["txt_Wallet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int txt_số_give_taki {
            get {
                return ((int)(this["txt_số_give_taki"]));
            }
            set {
                this["txt_số_give_taki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime time_server {
            get {
                return ((global::System.DateTime)(this["time_server"]));
            }
            set {
                this["time_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int donate_taki {
            get {
                return ((int)(this["donate_taki"]));
            }
            set {
                this["donate_taki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int donate_follow {
            get {
                return ((int)(this["donate_follow"]));
            }
            set {
                this["donate_follow"] = value;
            }
        }
    }
}
